// <auto-generated />
namespace Vidly_1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811161144379_fix2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
